---
- name: Development environment setup
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.git
    - hurricanehrndz.rustup
    - fubarhouse.golang
    - githubixx.kubectl
    - istvano.kustomize
    - andrewrothstein.kind
  tasks:
    - name: Install emacs
      apt:
        name: emacs
        state: latest
        update_cache: yes

    - name: Create .emacs.d/ directory
      file:
        path: ~/.emacs.d/
        state: directory
        mode: '0755'

    - name: Emacs configuration
      copy:
        src: init.el
        dest: ~/.emacs.d/init.el

    - name: Installing hugo static site generator
      apt:
        name: hugo
        state: latest
        update_cache: yes
