---
- name: Development environment setup
  hosts: all
  become: true
  vars:
    user: matthew
  roles:
    - geerlingguy.git
    - githubixx.kubectl
    - istvano.kustomize
    - andrewrothstein.kind
  tasks:
    - name: APT update
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install emacs
      apt:
        name: emacs
        state: present

    - name: Install docker
      import_role:
          name: geerlingguy.docker
      vars:
          docker_users:
            - "{{ user }}"
            
    - name: Install go
      import_role: 
          name: andrewrothstein.go
    
    - name: Install Hugo
      apt:
          name: hugo
          state: present
          
       
